#Build sdk version
FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY . .
RUN dotnet restore SRM.Services.Api/SRM.Services.Api.csproj
WORKDIR /src/SRM.Services.Api

ENTRYPOINT ["dotnet", "run"]
